name: .NET SpecFlow CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restaurar dependências
        run: dotnet restore

      - name: Compilar projeto
        run: dotnet build --no-restore

      - name: Rodar testes
        run: dotnet test --no-build --logger "trx"

       - name: Gerar relatório HTML com LivingDoc
        run: dotnet livingdoc feature-file --output TestResults/LivingDocReport.html

      - name: Salvar relatório de teste como artefato
        uses: actions/upload-artifact@v3
        with:
          name: livingdoc-report
          path: TestResults/LivingDocReport.html